---
customer: "dsz"
instance_name: "awstest"
instance_role: "lamp"
#instance_ansible_port: "22"
#instance_ansible_user: "ansible"
# ami RHEL-7.6_HVM_GA-20190128-x86_64-0-Hourly2-GP2
ami_id: "ami-000db10762d0c4c05"
ec2_environment: "Prod"
ec2_region: us-east-1
#ec2_current_url: a4b.us-east-1.amazonaws.com
vpc_name: demo-vpc
ec2_vpc_id: vpc-56ee8e2c
ec2_instance_type: t2.small
ec2_keypair: aws-dskp01
ec2_security_group: ds-aws-secugroup-01
ec2_security_group_id: "sg-054736dc13e58f941"
ec2_security_group_description: "New security for {{ ec2_environment }} Instances"
ec2_instance_count: 1
ec2_subnet_id: subnet-9e4414c2
os_type: "rhel"
