---
- name: Create a virtual machine from a template
  vmware_guest:
    hostname: "{{ var_esx_hostname }}"
    validate_certs: no
    #datacenter: "{{ var_datacenter }}"
    cluster: "{{ var_cluster }}"
    folder: "{{ var_vm_folder }}"
    name: "{{ var_vmname }}"
    state: "{{ var_state }}"
    template: "{{ var_vm_template }}"
    disk:
    - size_gb: "{{ var_disk_size_gb }}"
      type: "{{ var_disk_type }}"
      datastore: "{{ var_disk_datastore }}"
    hardware:
      memory_mb: "{{ var_vm_hw_memory_mb }}"
      num_cpus: "{{ var_vm_hw_num_cpus }}"
      num_cpu_cores_per_socket: "{{ var_vm_hw_num_cpu_cores_per_socket }}"
      scsi: "{{ var_vm_hw_scsi }}"
      #memory_reservation_lock: True
      #mem_limit: 8096
      #mem_reservation: 4096
      #cpu_limit: 8096
      #cpu_reservation: 4096
      #max_connections: 5
      hotadd_cpu: True
      hotremove_cpu: True
      hotadd_memory: False
      #version: 12 # Hardware version of virtual machine
      #boot_firmware: "efi"
    networks:
    - name: "{{ var_nic1_network }}"
      #mac: aa:bb:dd:aa:00:14
    wait_for_ip_address: yes
